# Generated by Django 4.1.1 on 2022-10-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_imagen', models.CharField(max_length=500, verbose_name='UrlImagen')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('cantidad', models.FloatField(verbose_name='Cantidad')),
                ('descripcion', models.CharField(default='Sin descripcion', max_length=2000, verbose_name='Descripcion')),
                ('precio', models.FloatField(verbose_name='Precio')),
            ],
        ),
    ]
