# Generated by Django 4.1.1 on 2022-10-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nombres', models.CharField(default='Sin nombres', max_length=50, verbose_name='Nombres')),
                ('apellidos', models.CharField(default='Sin apellidos', max_length=50, verbose_name='Apellidos')),
                ('ciudad', models.CharField(default='Sin ciudad', max_length=50, verbose_name='Ciudad')),
                ('password', models.CharField(default='Sin password', max_length=256, verbose_name='Password')),
                ('departamento', models.CharField(default='Sin departamento', max_length=50, verbose_name='Departamento')),
                ('direccion', models.CharField(default='Sin direccion', max_length=50, verbose_name='Direccion')),
                ('email', models.EmailField(default='Sin email', max_length=100, unique=True, verbose_name='Email')),
                ('telefono', models.CharField(default='Sin telefono', max_length=50, null=True, verbose_name='Telefono')),
                ('es_admin', models.BooleanField(default=False, verbose_name='EsAdmin')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
